kind: pipeline
name: scrapp-backend

steps:
  - name: test
    image: node:11-alpine
    commands:
      - npm install
      - npm run test

  - name: publish
    image: plugins/gcr
    settings:
      repo: getcolors/scrapp-backend
      dockerfile: Dockerfile
      tags: latest
      json_key:
        from_secret: google_credentials

  - name: deploy
    image: google/cloud-sdk:alpine
    only:
      - master
    script:
      - echo $google_credentials > /tmp/$CI_PIPELINE_ID.json
      - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
      - gcloud compute ssh goodhunt-backend
      - sudo docker run -d -p 80:3000 --restart always --env-file env.list gcr.io/getcolors/scrapp-backend:latest