version: '3'

#copia y pega en la raíz del proyecto con el nombre docker-compose.yml
#en tu copia puedes remover cualquier servicio para trabajar con el que quieras.

#no modifiques este archivo, siempre realiza una copia

services:
  api:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: ${database_name}
      POSTGRES_USER: ${database_user}
      POSTGRES_PASSWORD: ${database_password}
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database/scrapp.sql:/docker-entrypoint-initdb.d/scrapp.sql
