version: '3'



services:

  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: ${database_name}
      POSTGRES_USER: ${database_user}
      POSTGRES_PASSWORD: ${database_password}
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database/scrapp.sql:/docker-entrypoint-initdb.d/scrapp.sql